### ISSUE TITLE
Q1 Work Order - Data Access - May-June

### ISSUE THREAD

**Issue by j08lue** [EOEPCA/data-access#42]
## Task 1 – Requirements Analysis and Architectural Design​

- [ ] Refine use cases​
- [x] Define building block specification​
- [x] #5
- [ ] #3

## Task 2 – Detailed Design, Implementation, and V&V​

- [x] Provide initial documentation​ https://github.com/EOEPCA/data-access/issues/12
- [ ] Define a V&V Plan with Github Actions CI/CD pipeline for eoAPI​ https://github.com/developmentseed/eoapi-k8s/issues/85
- [ ] Setup CD pipeline for validation/integration environment (evaluation of ArgoCD) https://github.com/developmentseed/eoapi-k8s/issues/86
