### ISSUE TITLE
Define and conduct a V&V Plan with Github Actions CI/CD pipeline for eoAPI (based on RD BB) (Q2)

### ISSUE THREAD

**Issue by j08lue** [EOEPCA/data-access#60]
Q2 plan for

- https://github.com/EOEPCA/data-access/issues/41

## Sub-tasks

- [x] Run eoAPI tests in EOEPCA ArgoCD https://github.com/EOEPCA/eoepca-plus/pull/1
- [ ] https://github.com/developmentseed/eoapi-k8s/issues/88
- [ ] Run Stacture tests in EOEPCA ArgoCD
- [ ] Add testing docs to the RTD site
